export type VehicleCatalogItem = {
  id: string;
  catalogKey: string | null;
  vehicleSpecId: string | null;
  displayName: string;
  brand: string;
  model: string;
  variant: string;
  modelFamily: string | null;
  variantDisplayName: string | null;
  yearFrom: number | null;
  yearTo: number | null;
  officialSalesStatus: string | null;
  batteryNetKwh: number | null;
  batteryGrossKwh: number | null;
  wltpRangeKm: number | null;
  acMaxKw: number | null;
  dcMaxKw: number | null;
  driveType: string | null;
  vehicleClass: string | null;
  curbWeightKg: number | null;
  officialEfficiencyWhKm: number | null;
  recommendedDailySocMin: number | null;
  recommendedDailySocMax: number | null;
  heatPumpAvailable: boolean | null;
  heatPumpStandard: boolean | null;
  batteryChemistry: string | null;
  chargingPortType: string | null;
  towingCapacityKg: number | null;
  seats: number | null;
  sourceName: string | null;
  sourceUrl: string | null;
  imageUrl: string | null;
  brandImageUrl: string | null;
  verificationLevel: string | null;
  marketCode?: string;
  localDisplayName?: string | null;
  localSalesStatus?: string | null;
  marketSourceName?: string | null;
  marketSourceUrl?: string | null;
  marketVerificationLevel?: string | null;
};
