export type VehicleSpecRow = {
  id: string;
  canonical_vehicle_id: string;
  canonical_key: string;
  brand: string;
  model: string;
  variant: string;
  model_family: string | null;
  variant_display_name: string | null;
  year_from: number | null;
  year_to: number | null;
  official_sales_status: string | null;
  battery_gross_kwh: string | null;
  battery_net_kwh: string | null;
  wltp_range_km: number | null;
  ac_max_kw: string | null;
  dc_max_kw: string | null;
  drive_type: string | null;
  vehicle_class: string | null;
  curb_weight_kg: number | null;
  official_efficiency_wh_km: number | null;
  recommended_daily_soc_min: number | null;
  recommended_daily_soc_max: number | null;
  heat_pump_available: boolean | null;
  heat_pump_standard: boolean | null;
  battery_chemistry: string | null;
  charging_port_type: string | null;
  towing_capacity_kg: number | null;
  seats: number | null;
  source_name: string | null;
  source_url: string | null;
  image_url: string | null;
  brand_image_url: string | null;
  verification_level: string | null;
  market_code: string | null;
  local_display_name: string | null;
  local_sales_status: string | null;
  market_source_name: string | null;
  market_source_url: string | null;
  market_verification_level: string | null;
};

export type VehicleSpecDto = {
  id: string;
  catalogKey: string;
  vehicleSpecId: string;
  canonicalVehicleId: string;
  displayName: string;
  brand: string;
  model: string;
  variant: string;
  modelFamily: string | null;
  variantDisplayName: string | null;
  yearFrom: number | null;
  yearTo: number | null;
  officialSalesStatus: string | null;
  batteryGrossKwh: number | null;
  batteryNetKwh: number | null;
  wltpRangeKm: number | null;
  acMaxKw: number | null;
  dcMaxKw: number | null;
  driveType: string | null;
  vehicleClass: string | null;
  curbWeightKg: number | null;
  officialEfficiencyWhKm: number | null;
  recommendedDailySocMin: number | null;
  recommendedDailySocMax: number | null;
  heatPumpAvailable: boolean | null;
  heatPumpStandard: boolean | null;
  batteryChemistry: string | null;
  chargingPortType: string | null;
  towingCapacityKg: number | null;
  seats: number | null;
  sourceName: string | null;
  sourceUrl: string | null;
  imageUrl: string | null;
  brandImageUrl: string | null;
  verificationLevel: string | null;
  marketCode: string;
  localDisplayName: string | null;
  localSalesStatus: string | null;
  marketSourceName: string | null;
  marketSourceUrl: string | null;
  marketVerificationLevel: string | null;
};
